[2024-05-30T16:21:52.293+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T16:21:52.439+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: training_models.choose_best_model manual__2024-05-30T16:21:28.923643+00:00 [queued]>
[2024-05-30T16:21:52.479+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: training_models.choose_best_model manual__2024-05-30T16:21:28.923643+00:00 [queued]>
[2024-05-30T16:21:52.490+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-30T16:21:52.591+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2024-05-30 16:21:28.923643+00:00
[2024-05-30T16:21:52.621+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6846) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-30T16:21:52.628+0000] {standard_task_runner.py:63} INFO - Started process 6848 to run task
[2024-05-30T16:21:52.626+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'training_models', 'choose_best_model', 'manual__2024-05-30T16:21:28.923643+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/training_models.py', '--cfg-path', '/tmp/tmpe_r07ohu']
[2024-05-30T16:21:52.645+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask choose_best_model
[2024-05-30T16:21:52.832+0000] {task_command.py:426} INFO - Running <TaskInstance: training_models.choose_best_model manual__2024-05-30T16:21:28.923643+00:00 [running]> on host abdc8a9dc09e
[2024-05-30T16:21:53.202+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='training_models' AIRFLOW_CTX_TASK_ID='choose_best_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T16:21:28.923643+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-30T16:21:28.923643+00:00'
[2024-05-30T16:21:53.207+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T16:21:53.208+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-30T16:21:53.236+0000] {python.py:237} INFO - Done. Returned value was: accurate
[2024-05-30T16:21:53.238+0000] {branch.py:36} INFO - Branch into accurate
[2024-05-30T16:21:53.239+0000] {skipmixin.py:178} INFO - Following branch accurate
[2024-05-30T16:21:53.280+0000] {skipmixin.py:246} INFO - Skipping tasks [('inaccurate', -1)]
[2024-05-30T16:21:53.342+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T16:21:53.403+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=training_models, task_id=choose_best_model, run_id=manual__2024-05-30T16:21:28.923643+00:00, execution_date=20240530T162128, start_date=20240530T162152, end_date=20240530T162153
[2024-05-30T16:21:53.506+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-30T16:21:53.640+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-30T16:21:53.647+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
