[2024-05-30T16:22:00.469+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T16:22:00.569+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: training_models.accurate manual__2024-05-30T16:21:28.923643+00:00 [queued]>
[2024-05-30T16:22:00.600+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: training_models.accurate manual__2024-05-30T16:21:28.923643+00:00 [queued]>
[2024-05-30T16:22:00.602+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-30T16:22:00.669+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): accurate> on 2024-05-30 16:21:28.923643+00:00
[2024-05-30T16:22:00.707+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6849) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-30T16:22:00.715+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'training_models', 'accurate', 'manual__2024-05-30T16:21:28.923643+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/training_models.py', '--cfg-path', '/tmp/tmpp8f2u_t4']
[2024-05-30T16:22:00.736+0000] {standard_task_runner.py:63} INFO - Started process 6851 to run task
[2024-05-30T16:22:00.773+0000] {standard_task_runner.py:91} INFO - Job 56: Subtask accurate
[2024-05-30T16:22:00.963+0000] {task_command.py:426} INFO - Running <TaskInstance: training_models.accurate manual__2024-05-30T16:21:28.923643+00:00 [running]> on host abdc8a9dc09e
[2024-05-30T16:22:01.228+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='training_models' AIRFLOW_CTX_TASK_ID='accurate' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T16:21:28.923643+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-30T16:21:28.923643+00:00'
[2024-05-30T16:22:01.233+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T16:22:01.235+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-30T16:22:01.238+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'accurate'"]
[2024-05-30T16:22:01.260+0000] {subprocess.py:86} INFO - Output:
[2024-05-30T16:22:01.265+0000] {subprocess.py:93} INFO - accurate
[2024-05-30T16:22:01.267+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-30T16:22:01.269+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T16:22:01.325+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=training_models, task_id=accurate, run_id=manual__2024-05-30T16:21:28.923643+00:00, execution_date=20240530T162128, start_date=20240530T162200, end_date=20240530T162201
[2024-05-30T16:22:01.397+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-30T16:22:01.448+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-30T16:22:01.453+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
