[2024-05-29T15:51:16.588+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T15:51:16.615+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.choose_best_model manual__2024-05-29T15:51:10.612504+00:00 [queued]>
[2024-05-29T15:51:16.624+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.choose_best_model manual__2024-05-29T15:51:10.612504+00:00 [queued]>
[2024-05-29T15:51:16.625+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T15:51:16.642+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2024-05-29 15:51:10.612504+00:00
[2024-05-29T15:51:16.656+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=908) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T15:51:16.659+0000] {standard_task_runner.py:63} INFO - Started process 910 to run task
[2024-05-29T15:51:16.659+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'choose_best_model', 'manual__2024-05-29T15:51:10.612504+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmp5z0o3s35']
[2024-05-29T15:51:16.663+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask choose_best_model
[2024-05-29T15:51:16.716+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag.choose_best_model manual__2024-05-29T15:51:10.612504+00:00 [running]> on host abdc8a9dc09e
[2024-05-29T15:51:16.814+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='choose_best_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-29T15:51:10.612504+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-29T15:51:10.612504+00:00'
[2024-05-29T15:51:16.816+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T15:51:16.817+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-29T15:51:16.827+0000] {python.py:237} INFO - Done. Returned value was: accurate
[2024-05-29T15:51:16.828+0000] {branch.py:36} INFO - Branch into accurate
[2024-05-29T15:51:16.829+0000] {skipmixin.py:178} INFO - Following branch accurate
[2024-05-29T15:51:16.845+0000] {skipmixin.py:246} INFO - Skipping tasks [('inaccurate', -1)]
[2024-05-29T15:51:16.872+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T15:51:16.893+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=choose_best_model, run_id=manual__2024-05-29T15:51:10.612504+00:00, execution_date=20240529T155110, start_date=20240529T155116, end_date=20240529T155116
[2024-05-29T15:51:16.915+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T15:51:16.942+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-29T15:51:16.946+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
