[2024-05-30T07:49:48.621+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T07:49:48.676+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testing_dag.inaccurate manual__2024-05-30T07:49:34.909321+00:00 [queued]>
[2024-05-30T07:49:48.695+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testing_dag.inaccurate manual__2024-05-30T07:49:34.909321+00:00 [queued]>
[2024-05-30T07:49:48.697+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-30T07:49:48.722+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): inaccurate> on 2024-05-30 07:49:34.909321+00:00
[2024-05-30T07:49:48.736+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3230) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-30T07:49:48.739+0000] {standard_task_runner.py:63} INFO - Started process 3232 to run task
[2024-05-30T07:49:48.740+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'testing_dag', 'inaccurate', 'manual__2024-05-30T07:49:34.909321+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/training_models.py', '--cfg-path', '/tmp/tmp8m91c3s3']
[2024-05-30T07:49:48.744+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask inaccurate
[2024-05-30T07:49:48.826+0000] {task_command.py:426} INFO - Running <TaskInstance: testing_dag.inaccurate manual__2024-05-30T07:49:34.909321+00:00 [running]> on host abdc8a9dc09e
[2024-05-30T07:49:49.143+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='testing_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T07:49:34.909321+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-30T07:49:34.909321+00:00'
[2024-05-30T07:49:49.148+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T07:49:49.150+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-30T07:49:49.151+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2024-05-30T07:49:49.174+0000] {subprocess.py:86} INFO - Output:
[2024-05-30T07:49:49.177+0000] {subprocess.py:93} INFO - inaccurate
[2024-05-30T07:49:49.178+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-30T07:49:49.179+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T07:49:49.218+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=testing_dag, task_id=inaccurate, run_id=manual__2024-05-30T07:49:34.909321+00:00, execution_date=20240530T074934, start_date=20240530T074948, end_date=20240530T074949
[2024-05-30T07:49:49.277+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-30T07:49:49.354+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-30T07:49:49.363+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
