[2024-05-30T07:33:41.699+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T07:33:41.785+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testing_dag.inaccurate manual__2024-05-30T07:33:27.562335+00:00 [queued]>
[2024-05-30T07:33:41.802+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testing_dag.inaccurate manual__2024-05-30T07:33:27.562335+00:00 [queued]>
[2024-05-30T07:33:41.804+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-30T07:33:41.828+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): inaccurate> on 2024-05-30 07:33:27.562335+00:00
[2024-05-30T07:33:41.839+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3030) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-30T07:33:41.841+0000] {standard_task_runner.py:63} INFO - Started process 3032 to run task
[2024-05-30T07:33:41.842+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'testing_dag', 'inaccurate', 'manual__2024-05-30T07:33:27.562335+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/training_models.py', '--cfg-path', '/tmp/tmp6acp5jkj']
[2024-05-30T07:33:41.846+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask inaccurate
[2024-05-30T07:33:41.940+0000] {task_command.py:426} INFO - Running <TaskInstance: testing_dag.inaccurate manual__2024-05-30T07:33:27.562335+00:00 [running]> on host abdc8a9dc09e
[2024-05-30T07:33:42.148+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='testing_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T07:33:27.562335+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-30T07:33:27.562335+00:00'
[2024-05-30T07:33:42.154+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T07:33:42.156+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-30T07:33:42.159+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2024-05-30T07:33:42.190+0000] {subprocess.py:86} INFO - Output:
[2024-05-30T07:33:42.194+0000] {subprocess.py:93} INFO - inaccurate
[2024-05-30T07:33:42.196+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-30T07:33:42.198+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T07:33:42.313+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=testing_dag, task_id=inaccurate, run_id=manual__2024-05-30T07:33:27.562335+00:00, execution_date=20240530T073327, start_date=20240530T073341, end_date=20240530T073342
[2024-05-30T07:33:42.420+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-30T07:33:42.523+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-30T07:33:42.540+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
