[2024-05-29T15:43:24.882+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T15:43:24.923+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2024-05-28T00:00:00+00:00 [queued]>
[2024-05-29T15:43:24.936+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2024-05-28T00:00:00+00:00 [queued]>
[2024-05-29T15:43:24.938+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T15:43:24.959+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): inaccurate> on 2024-05-28 00:00:00+00:00
[2024-05-29T15:43:24.967+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=776) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T15:43:24.969+0000] {standard_task_runner.py:63} INFO - Started process 781 to run task
[2024-05-29T15:43:24.970+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2024-05-28T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmpor64x1kb']
[2024-05-29T15:43:24.975+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask inaccurate
[2024-05-29T15:43:25.050+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2024-05-28T00:00:00+00:00 [running]> on host abdc8a9dc09e
[2024-05-29T15:43:25.174+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-28T00:00:00+00:00'
[2024-05-29T15:43:25.176+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T15:43:25.177+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-29T15:43:25.178+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2024-05-29T15:43:25.190+0000] {subprocess.py:86} INFO - Output:
[2024-05-29T15:43:25.192+0000] {subprocess.py:93} INFO - inaccurate
[2024-05-29T15:43:25.193+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-29T15:43:25.194+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T15:43:25.227+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, run_id=scheduled__2024-05-28T00:00:00+00:00, execution_date=20240528T000000, start_date=20240529T154324, end_date=20240529T154325
[2024-05-29T15:43:25.266+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T15:43:25.288+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-29T15:43:25.294+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
