[2024-05-30T07:49:43.585+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T07:49:43.624+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testing_dag.choose_best_model manual__2024-05-30T07:49:34.909321+00:00 [queued]>
[2024-05-30T07:49:43.639+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testing_dag.choose_best_model manual__2024-05-30T07:49:34.909321+00:00 [queued]>
[2024-05-30T07:49:43.640+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-30T07:49:43.667+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2024-05-30 07:49:34.909321+00:00
[2024-05-30T07:49:43.678+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3227) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-30T07:49:43.680+0000] {standard_task_runner.py:63} INFO - Started process 3229 to run task
[2024-05-30T07:49:43.682+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'testing_dag', 'choose_best_model', 'manual__2024-05-30T07:49:34.909321+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/training_models.py', '--cfg-path', '/tmp/tmpe5qrtnkz']
[2024-05-30T07:49:43.687+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask choose_best_model
[2024-05-30T07:49:43.775+0000] {task_command.py:426} INFO - Running <TaskInstance: testing_dag.choose_best_model manual__2024-05-30T07:49:34.909321+00:00 [running]> on host abdc8a9dc09e
[2024-05-30T07:49:43.929+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='testing_dag' AIRFLOW_CTX_TASK_ID='choose_best_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T07:49:34.909321+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-30T07:49:34.909321+00:00'
[2024-05-30T07:49:43.933+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T07:49:43.934+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-30T07:49:43.953+0000] {python.py:237} INFO - Done. Returned value was: inaccurate
[2024-05-30T07:49:43.954+0000] {branch.py:36} INFO - Branch into inaccurate
[2024-05-30T07:49:43.955+0000] {skipmixin.py:178} INFO - Following branch inaccurate
[2024-05-30T07:49:43.984+0000] {skipmixin.py:246} INFO - Skipping tasks [('accurate', -1)]
[2024-05-30T07:49:44.037+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T07:49:44.083+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=testing_dag, task_id=choose_best_model, run_id=manual__2024-05-30T07:49:34.909321+00:00, execution_date=20240530T074934, start_date=20240530T074943, end_date=20240530T074944
[2024-05-30T07:49:44.138+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-30T07:49:44.263+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-30T07:49:44.272+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
