[2024-05-30T07:55:01.081+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T07:55:01.169+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: training_models.choose_best_model manual__2024-05-30T07:54:52.325279+00:00 [queued]>
[2024-05-30T07:55:01.198+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: training_models.choose_best_model manual__2024-05-30T07:54:52.325279+00:00 [queued]>
[2024-05-30T07:55:01.210+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-30T07:55:01.278+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2024-05-30 07:54:52.325279+00:00
[2024-05-30T07:55:01.306+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3312) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-30T07:55:01.317+0000] {standard_task_runner.py:63} INFO - Started process 3316 to run task
[2024-05-30T07:55:01.321+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'training_models', 'choose_best_model', 'manual__2024-05-30T07:54:52.325279+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/training_models.py', '--cfg-path', '/tmp/tmprq6zwmyh']
[2024-05-30T07:55:01.333+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask choose_best_model
[2024-05-30T07:55:01.510+0000] {task_command.py:426} INFO - Running <TaskInstance: training_models.choose_best_model manual__2024-05-30T07:54:52.325279+00:00 [running]> on host abdc8a9dc09e
[2024-05-30T07:55:01.908+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='training_models' AIRFLOW_CTX_TASK_ID='choose_best_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T07:54:52.325279+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-30T07:54:52.325279+00:00'
[2024-05-30T07:55:01.916+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T07:55:01.918+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-30T07:55:01.968+0000] {python.py:237} INFO - Done. Returned value was: inaccurate
[2024-05-30T07:55:01.970+0000] {branch.py:36} INFO - Branch into inaccurate
[2024-05-30T07:55:01.972+0000] {skipmixin.py:178} INFO - Following branch inaccurate
[2024-05-30T07:55:02.067+0000] {skipmixin.py:246} INFO - Skipping tasks [('accurate', -1)]
[2024-05-30T07:55:02.171+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T07:55:02.266+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=training_models, task_id=choose_best_model, run_id=manual__2024-05-30T07:54:52.325279+00:00, execution_date=20240530T075452, start_date=20240530T075501, end_date=20240530T075502
[2024-05-30T07:55:02.388+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-30T07:55:02.450+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-30T07:55:02.455+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
